# Generated by Django 6.0.4 on 2026-08-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Ranking',
            fields=[
                ('res_ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Ranking',
            fields=[
                ('dish_ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish')),
            ],
        ),
    ]
