# Generated by Django 6.0.4 on 2026-04-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('acc_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_profile_photo', models.ImageField(blank=True, null=True, upload_to='account_photos/')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accounttype')),
            ],
        ),
    ]
