# Generated by Django 6.0.4 on 2026-08-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_description', models.TextField(blank=True, null=True)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_signature', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_notes', models.TextField(blank=True, null=True)),
                ('how_to_eat', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Category',
            fields=[
                ('dish_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_category_name', models.CharField(max_length=255)),
                ('dish_category_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Images',
            fields=[
                ('dish_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_image_path', models.ImageField(upload_to='dish_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
